test:
	testchart run --namespace my-namespace --release my-release --app-version 1.0.0 --chart-version 1.0.0

update:
	testchart update --namespace my-namespace --release my-release --app-version 1.0.0 --chart-version 1.0.0
